"""initial schema

Revision ID: 2c89fea45c0f
Revises:
Create Date: 2026-09-13 15:55:52.507768

"""

from collections.abc import Sequence

import sqlalchemy as sa
import app.db_types
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "2c89fea45c0f"
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "applications",
        sa.Column("app_name", sa.String(length=255), nullable=False),
        sa.Column(
            "app_type",
            sa.Enum("IN_HOUSE", "COTS", "MOBILE", "API", name="app_type"),
            nullable=False,
        ),
        sa.Column("owner_team", sa.String(length=255), nullable=False),
        sa.Column("tech_lead_contact", sa.String(length=255), nullable=True),
        sa.Column("business_unit", sa.String(length=255), nullable=True),
        sa.Column(
            "criticality",
            sa.Enum("CRITICAL", "HIGH", "MEDIUM", "LOW", name="criticality"),
            nullable=False,
        ),
        sa.Column(
            "environment",
            sa.Enum("PRODUCTION", "STAGING", "DEV", name="environment"),
            nullable=False,
        ),
        sa.Column("internet_facing", sa.Boolean(), nullable=False),
        sa.Column("data_classification", sa.String(length=255), nullable=True),
        sa.Column("repo_url", sa.String(length=1024), nullable=True),
        sa.Column("jira_project_key", sa.String(length=64), nullable=True),
        sa.Column("sdp_category", sa.String(length=255), nullable=True),
        sa.Column("owner_email", sa.String(length=255), nullable=True),
        sa.Column("ownership_confirmed", sa.Boolean(), nullable=False),
        sa.Column("id", app.db_types.GUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_applications_app_name"), "applications", ["app_name"], unique=False)
    op.create_index(
        op.f("ix_applications_owner_team"), "applications", ["owner_team"], unique=False
    )
    op.create_table(
        "audit_logs",
        sa.Column("action", sa.String(length=255), nullable=False),
        sa.Column("actor", sa.String(length=255), nullable=False),
        sa.Column("entity_type", sa.String(length=64), nullable=False),
        sa.Column("entity_id", sa.String(length=64), nullable=False),
        sa.Column("before_value", sa.JSON(), nullable=True),
        sa.Column("after_value", sa.JSON(), nullable=True),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", app.db_types.GUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "APPSEC", "DEV_TEAM", "LEGAL", "MANAGEMENT", "AUDIT", "ADMIN", name="user_role"
            ),
            nullable=False,
        ),
        sa.Column("owner_team", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", app.db_types.GUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "app_versions",
        sa.Column("application_id", app.db_types.GUID(), nullable=False),
        sa.Column("version_label", sa.String(length=255), nullable=False),
        sa.Column("commit_sha", sa.String(length=64), nullable=True),
        sa.Column(
            "environment",
            sa.Enum("PRODUCTION", "STAGING", "DEV", name="version_environment"),
            nullable=False,
        ),
        sa.Column("is_current_production", sa.Boolean(), nullable=False),
        sa.Column("last_ingested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_stale", sa.Boolean(), nullable=False),
        sa.Column("id", app.db_types.GUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["application_id"], ["applications.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "components",
        sa.Column("app_version_id", app.db_types.GUID(), nullable=False),
        sa.Column("component_name", sa.String(length=512), nullable=False),
        sa.Column("version", sa.String(length=255), nullable=True),
        sa.Column("license", sa.String(length=255), nullable=True),
        sa.Column("scope", sa.String(length=32), nullable=False),
        sa.Column("purl", sa.String(length=1024), nullable=True),
        sa.Column("id", app.db_types.GUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["app_version_id"], ["app_versions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_components_component_name"), "components", ["component_name"], unique=False
    )
    op.create_table(
        "go_live_approvals",
        sa.Column("app_version_id", app.db_types.GUID(), nullable=False),
        sa.Column("sbom_pass", sa.Boolean(), nullable=False),
        sa.Column("sast_pass", sa.Boolean(), nullable=False),
        sa.Column("pentest_pass", sa.Boolean(), nullable=False),
        sa.Column("approver", sa.String(length=255), nullable=False),
        sa.Column("is_break_glass", sa.Boolean(), nullable=False),
        sa.Column("id", app.db_types.GUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["app_version_id"], ["app_versions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pentest_projects",
        sa.Column("app_version_id", app.db_types.GUID(), nullable=False),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("engagement_type", sa.String(length=32), nullable=False),
        sa.Column("vendor_name", sa.String(length=255), nullable=True),
        sa.Column("contract_ref", sa.String(length=255), nullable=True),
        sa.Column("cost", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=8), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("report_file_url", sa.String(length=1024), nullable=True),
        sa.Column("id", app.db_types.GUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["app_version_id"], ["app_versions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "scan_results",
        sa.Column("app_version_id", app.db_types.GUID(), nullable=False),
        sa.Column("scan_type", sa.String(length=32), nullable=False),
        sa.Column("scanned_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("result_status", sa.String(length=64), nullable=False),
        sa.Column("is_manual_upload", sa.Boolean(), nullable=False),
        sa.Column("uploaded_by", sa.String(length=255), nullable=True),
        sa.Column("report_file_url", sa.String(length=1024), nullable=True),
        sa.Column("validity_expiry_date", sa.Date(), nullable=True),
        sa.Column("id", app.db_types.GUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["app_version_id"], ["app_versions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "findings",
        sa.Column("component_id", app.db_types.GUID(), nullable=False),
        sa.Column("cve_id", sa.String(length=64), nullable=False),
        sa.Column("cvss", sa.Float(), nullable=True),
        sa.Column("epss", sa.Float(), nullable=True),
        sa.Column("kev_flag", sa.Boolean(), nullable=False),
        sa.Column(
            "severity_tier",
            sa.Enum("CRITICAL", "HIGH", "MEDIUM", "LOW", name="severity_tier"),
            nullable=False,
        ),
        sa.Column(
            "vex_status",
            sa.Enum("AFFECTED", "NOT_AFFECTED", "FIXED", "UNDER_INVESTIGATION", name="vex_status"),
            nullable=False,
        ),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("id", app.db_types.GUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["component_id"], ["components.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_findings_cve_id"), "findings", ["cve_id"], unique=False)
    op.create_table(
        "tickets",
        sa.Column("finding_id", app.db_types.GUID(), nullable=False),
        sa.Column("external_system", sa.String(length=64), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("id", app.db_types.GUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["finding_id"], ["findings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "waivers",
        sa.Column("finding_id", app.db_types.GUID(), nullable=False),
        sa.Column("requested_by", sa.String(length=255), nullable=False),
        sa.Column("approved_by", sa.String(length=255), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("expiry_date", sa.Date(), nullable=False),
        sa.Column(
            "status", sa.Enum("ACTIVE", "EXPIRED", "REVOKED", name="waiver_status"), nullable=False
        ),
        sa.Column("id", app.db_types.GUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["finding_id"], ["findings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("waivers")
    op.drop_table("tickets")
    op.drop_index(op.f("ix_findings_cve_id"), table_name="findings")
    op.drop_table("findings")
    op.drop_table("scan_results")
    op.drop_table("pentest_projects")
    op.drop_table("go_live_approvals")
    op.drop_index(op.f("ix_components_component_name"), table_name="components")
    op.drop_table("components")
    op.drop_table("app_versions")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_applications_owner_team"), table_name="applications")
    op.drop_index(op.f("ix_applications_app_name"), table_name="applications")
    op.drop_table("applications")
    # ### end Alembic commands ###

    # On PostgreSQL an enum type outlives the table that used it, so DROP TABLE alone
    # leaves these behind and a later `upgrade` fails with "type already exists".
    # No-op on dialects without native enums (e.g. SQLite).
    bind = op.get_bind()
    for enum_name in (
        "app_type",
        "criticality",
        "environment",
        "version_environment",
        "user_role",
        "severity_tier",
        "vex_status",
        "waiver_status",
    ):
        sa.Enum(name=enum_name).drop(bind, checkfirst=True)
