"""integration connectors and ticket lifecycle fields

Revision ID: e417e1e6a154
Revises: ed804b338ac7
Create Date: 2026-09-13 23:25:13.823340

"""

from collections.abc import Sequence

import sqlalchemy as sa
import app.db_types
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "e417e1e6a154"
down_revision: str | None = "ed804b338ac7"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None

CONNECTOR_TYPE = sa.Enum("JIRA", "SERVICE_DESK_PLUS", "GENERIC_WEBHOOK", name="connector_type")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "integration_connectors",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("connector_type", CONNECTOR_TYPE, nullable=False),
        sa.Column("base_url", sa.String(length=1024), nullable=False),
        sa.Column("auth_token", sa.String(length=1024), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("routing_severities", sa.JSON(), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("id", app.db_types.GUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    with op.batch_alter_table("tickets", schema=None) as batch_op:
        batch_op.add_column(sa.Column("connector_id", app.db_types.GUID(), nullable=True))
        batch_op.add_column(sa.Column("last_error", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True))
        # server_default lets this NOT NULL column be added to a table that may already
        # hold rows; the model itself has no server_default (only a Python-side one), so
        # it is dropped again once every existing row has a concrete value.
        batch_op.add_column(
            sa.Column("retry_count", sa.Integer(), nullable=False, server_default="0")
        )
        batch_op.create_foreign_key(
            "fk_tickets_connector_id",
            "integration_connectors",
            ["connector_id"],
            ["id"],
            ondelete="SET NULL",
        )
    with op.batch_alter_table("tickets", schema=None) as batch_op:
        batch_op.alter_column("retry_count", server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tickets", schema=None) as batch_op:
        batch_op.drop_constraint("fk_tickets_connector_id", type_="foreignkey")
        batch_op.drop_column("retry_count")
        batch_op.drop_column("last_synced_at")
        batch_op.drop_column("last_error")
        batch_op.drop_column("connector_id")

    op.drop_table("integration_connectors")
    # Postgres enum types outlive the table that used them (unlike SQLite, which has no
    # native enum) — drop it explicitly so a later upgrade does not fail on "type already
    # exists". No-op on dialects without native enums.
    CONNECTOR_TYPE.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
